name: Build mod
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip -q *.zip
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 4.9
      - run: cd mod && gradle setupCIWorkspace build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: prostymod-jar
          path: mod/build/libs/*.jar
